### ISSUE TITLE
Ask about s01 during template initialization?

### ISSUE THREAD

**Issue by armanbilge** [valencik/proto-typelevel.g8#4]
This thing.

```scala
// true by default, set to false to publish to s01.oss.sonatype.org
ThisBuild / tlSonatypeUseLegacyHost := true
```

I wonder if more projects want `false` these days. Typelevel itself has moved to s01.

**Comment by valencik** [comment]
If you were setting up sonatype publishing from scratch for the first time, would you go with s01?

**Comment by armanbilge** [comment]
All domains registered with sonatype after February 2021 are on S01. Old domains have the option to migrate (as typelevel did).

https://typelevel.org/sbt-typelevel/secrets.html#sonatype-credentials

**Comment by valencik** [comment]
Ok, going with s01 publishing by default in f729dde87d73040ddbf95387362a82b3946bb13d.

Going to try and keep the input params slim if possible.

**Comment by armanbilge** [comment]
LGTM! :)
