### ISSUE TITLE
GitHub workflows are missing

### ISSUE THREAD

**Issue by armanbilge** [valencik/proto-typelevel.g8#5]
https://github.com/valencik/proto-typelevel.g8/blob/8f176566bfebe5edb0ef535b548041b1f67a4b18/src/main/g8/default.properties#L16

We can also check this in CI with `githubWorkflowCheck`.

**Comment by valencik** [comment]
Oh, good catch!
Added in a330d8e96bfe31e87a73f283a7add0553bcdcb91 and tested in 314ebcaac074196694850a6b8b1aae69b2a4e90d
